replicaCount: 1

image:
  repository: hotelier-availability-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: "nginx"
  hosts: []

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

env: {}

secretRef: "hotelier-secrets"

serviceMonitor:
  enabled: false
  interval: "30s"
